Feature/micronutrient powders
nrf-mamas-hub/mamashub-web pull request #50
Opened 2024-12-17 22:04 UTC by Faqih001

## Description

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactor (code changes that neither fix a bug nor add a feature)
- [ ] Other (please specify):

## Checklist

- [ ] I have followed the coding standards for this project.
- [ ] My code has been linted and formatted.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have updated the documentation, if necessary.
- [ ] The changes require review by another team member (add reviewer).

## How Has This Been Tested?

## Related Issues

## Screenshots or GIFs (if applicable)
[MicronutrientPowders](https://github.com/user-attachments/assets/8e146947-133a-405e-8c44-2ac8d6bbd8f1)

## Further Comments

2024-12-17 22:05 UTC, Faqih001 commented
Check the push I have made on micronutrient powders

2024-12-18 11:32 UTC, 1wes requested changes
You pushed files for the special care form, though I have resolved conflicts since that form's PR was already merged to the hackathon branch. However, I cannot merge this PR with the altered package-lock.json. Remove it and push the changes.

2024-12-18 11:32 UTC, 1wes commented on package-lock.json
Remove this commit. If you tinkered with the dependencies, they should only be applicable to your local instance. Pushing them here will affect the whole repo for everyone @Faqih001

2025-04-10 05:47 UTC, DavidSaruni approved these changes
Solved the conflicting routes file and this can be merged now

2025-04-10 06:04 UTC, 1wes approved these changes
Once these changes are approved, ensure you pull the latest changes from the upstream branch @Faqih001 to have an accurate package.json file. Otherwise, if @DavidSaruni has approved, then it can be merged

2025-04-10 06:04 UTC, 1wes commented
@DavidSaruni , proceed to merge

2025-04-10 06:17 UTC, DavidSaruni commented
> @DavidSaruni , proceed to merge. And for clarity's sake in the future, enforce a one commit per pull request from now onwards

Thank you senior I will

2025-04-10 06:17 UTC, merged